CREATE TABLE REDBUS_USERS (
  USER_ID NUMBER ,
  NAME VARCHAR2(150) ,
  EMAIL VARCHAR2(50) ,
  PHONE VARCHAR2(13) ,
  ADDRESS VARCHAR2(200) ,
  PASSWORD VARCHAR2(150) ,
  RULE VARCHAR2(10) 
);

INSERT INTO REDBUS_USERS (user_id, name, email, phone, address, password, rule) VALUES
(1, 'SASI', 'sasi@gmail.com', '7708016544', 'chennai', 'sasi', 'passenger');

INSERT INTO REDBUS_USERS (user_id, name, email, phone, address, password, rule) VALUES
(2, 'ADMIN', 'admin@gmail.com', '9192929292', 'chennai', '123', 'admin');

CREATE TABLE BUSES (
  BUS_ID number ,
  BUS_NO VARCHAR2(30) ,
  NAME VARCHAR2(50) ,
  TOTAL_SEAT number ,
  TYPE VARCHAR2(20)  
); 

INSERT INTO BUSES (BUS_ID, BUS_NO, NAME, TOTAL_SEAT, TYPE) VALUES
(1, 'TN09AP5522', 'SRM TRAVELS', 20, 'SLEEPER');

INSERT INTO BUSES (BUS_ID, BUS_NO, NAME, TOTAL_SEAT, TYPE) VALUES
(2, 'TN09ZP9922', 'SUNDRA TRAVELS', 20, 'SLEEPER');

CREATE TABLE STATIONS (
  STATION_ID NUMBER ,
  NAME VARCHAR2(50) ,
  ADDRESS VARCHAR2(70) ,
  CONTACT VARCHAR2(20) 
) ;

INSERT INTO STATIONS (STATION_ID, NAME, ADDRESS, CONTACT) VALUES
(1, 'CHENNAI', 'CMBT', '01733435951');

INSERT INTO STATIONS (STATION_ID, NAME, ADDRESS, CONTACT) VALUES
(2, 'BANGLORE', 'ELECTRONIC CITY', '01733435951');


CREATE TABLE DESTINATIONS (
  DESTINATION_ID NUMBER ,
  STATION_FROM NUMBER ,
  STATION_TO NUMBER ,
  BUS_ID NUMBER ,
  TIME VARCHAR2(30) ,
  STATUS VARCHAR2(20) ,
  FARE VARCHAR2(5) 
);

INSERT INTO DESTINATIONS (DESTINATION_ID, STATION_FROM, STATION_TO, BUS_ID, TIME, STATUS, FARE) VALUES
(1, 1, 2, 1, '4:30Am', 'active', '600');

INSERT INTO DESTINATIONS (DESTINATION_ID, STATION_FROM, STATION_TO, BUS_ID, TIME, STATUS, FARE) VALUES
(2, 1, 2, 2, '5:30Am', 'active', '650');

CREATE TABLE BOOKING (
  BOOKING_ID NUMBER ,
  DESTINATION_ID NUMBER ,
  BOOKING_DATE VARCHAR2(30) ,
  JOURNEY_DATE VARCHAR2(30) ,
  BUS_ID NUMBER ,
  SEAT_NUMBERS VARCHAR2(150) ,
  PASSENGER_ID NUMBER ,
  NUMBER_OF_SEAT NUMBER ,
  STATUS VARCHAR2(10) 
);

INSERT INTO BOOKING (BOOKING_ID, DESTINATION_ID, BOOKING_DATE, JOURNEY_DATE, BUS_ID, SEAT_NUMBERS, PASSENGER_ID, NUMBER_OF_SEAT, STATUS) VALUES
(1, 1, '12-02-2020', '12-02-2020', 1, '1,2', 1, 2, 'SUCCESS');

INSERT INTO BOOKING (BOOKING_ID, DESTINATION_ID, BOOKING_DATE, JOURNEY_DATE, BUS_ID, SEAT_NUMBERS, PASSENGER_ID, NUMBER_OF_SEAT, STATUS) VALUES
(2, 1, '12-02-2020', '12-02-2020', 1, '3,4', 1, 2, 'SUCCESS');

INSERT INTO BOOKING (BOOKING_ID, DESTINATION_ID, BOOKING_DATE, JOURNEY_DATE, BUS_ID, SEAT_NUMBERS, PASSENGER_ID, NUMBER_OF_SEAT, STATUS) VALUES
(3, 1, '12-02-2020', '12-02-2020', 2, '1,2', 1, 2, 'SUCCESS');

INSERT INTO BOOKING (BOOKING_ID, DESTINATION_ID, BOOKING_DATE, JOURNEY_DATE, BUS_ID, SEAT_NUMBERS, PASSENGER_ID, NUMBER_OF_SEAT, STATUS) VALUES
(4, 1, '12-02-2020', '12-02-2020', 2, '3,4', 1, 2, 'SUCCESS');

CREATE SEQUENCE REDBUS_USER_ID_SEQ START WITH 3;  

CREATE SEQUENCE DESTINATION_ID_SEQ START WITH 3;  

CREATE SEQUENCE STATION_ID_SEQ START WITH 3;  

CREATE SEQUENCE BOOKING_ID_SEQ START WITH 5;  

CREATE SEQUENCE BUS_ID_SEQ START WITH 3; 